name: main
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
  check-format:
    name: Check Format
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
      - name: Check Format
        run: npm run format:check
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint
        run: npm run lint -- --custom-formatter 'node_modules/stylelint-junit-formatter' -o reports/lint-results.xml
      - name: Upload Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: lint-results
          path: reports/lint-results.xml
  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - check-format
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        run: bundle exec jekyll build
        env:
          JEKYLL_GITHUB_TOKEN: ${{ secrets.JEKYLL_GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: site
          path: _site
