name: main
on:
  push:
    branches:
      - main
jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
  pre-build:
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Check Format
            task: yarn format:check
          - name: Lint
            task: yarn lint
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
      - run: ${{ matrix.task }}
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [pre-build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - run: bundle exec jekyll build
        env:
          JEKYLL_GITHUB_TOKEN: ${{ secrets.JEKYLL_GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: site
          path: _site
